'use client';

import type { Order, Quote } from '@/lib/crm-store';
import { amountInWords } from '@/lib/number-to-words';
import { defaultCurrency } from '@/lib/currencies';

type PdfLocale = 'fr' | 'en' | 'ar';

function pdfT(locale: PdfLocale | string | undefined) {
  const l = (locale || 'fr') as PdfLocale;
  const isAr = l === 'ar';
  const isEn = l === 'en';
  return {
    // Document shell
    issuer: isAr ? 'المصدر' : isEn ? 'Issuer' : 'Émetteur',
    client: isAr ? 'العميل' : isEn ? 'Client' : 'Client',
    document: isAr ? 'المستند' : isEn ? 'Document' : 'Document',
    date: isAr ? 'التاريخ' : isEn ? 'Date' : 'Date',
    ref: isAr ? 'المرجع' : isEn ? 'Ref.' : 'Réf.',
    validity: isAr ? 'الصلاحية' : isEn ? 'Validity' : 'Validité',
    status: isAr ? 'الحالة' : isEn ? 'Status' : 'Statut',
    paymentMode: isAr ? 'طريقة الدفع' : isEn ? 'Payment method' : 'Mode paiement',
    address: isAr ? 'العنوان' : isEn ? 'Address' : 'Adresse',
    phone: isAr ? 'الهاتف' : isEn ? 'Phone' : 'Tél',
    // Headers
    headers: isAr ? ['المادة','الكمية','سعر الوحدة دون ضريبة','الخصم','المجموع دون ضريبة'] : isEn ? ['Item','Qty','Unit price excl. tax','Discount','Total excl. tax'] : ['Article','Qté','Prix unit. HT','Remise','Total HT'],
    // Breakdown
    subtotal: isAr ? 'المجموع الفرعي دون ضريبة' : isEn ? 'Subtotal excl. tax' : 'Sous-total HT',
    productDiscount: isAr ? 'خصم المنتجات' : isEn ? 'Product discount' : 'Remises produits',
    globalDiscount: isAr ? 'الخصم العام' : isEn ? 'Global discount' : 'Remise globale',
    couponDiscount: (coupon:string)=> isAr ? `القسيمة ${coupon}`.trim() : isEn ? `Coupon ${coupon}`.trim() : `Coupon ${coupon}`.trim(),
    discount: isAr ? 'الخصم' : isEn ? 'Discount' : 'Remise',
    discounts: isAr ? 'الخصومات' : isEn ? 'Discounts' : 'Remises',
    productShipping: isAr ? 'شحن المنتجات' : isEn ? 'Product shipping' : 'Livraison articles',
    globalShipping: isAr ? 'الشحن حسب المنطقة' : isEn ? 'Zone shipping' : 'Livraison zone',
    shipping: isAr ? 'الشحن' : isEn ? 'Shipping' : 'Livraison',
    tax: isAr ? 'الضرائب / القيمة المضافة' : isEn ? 'Taxes' : 'TVA / Taxes',
    taxBase: isAr ? 'الوعاء الضريبي' : isEn ? 'Taxable base' : 'Assiette',
    taxBaseRate: (rate:number, included?:boolean)=> {
      const suf = included ? (isAr ? ' (متضمنة)' : isEn ? ' (incl.)' : ' (incl.)') : '';
      if (isAr) return `الوعاء ${rate}%${suf}`;
      if (isEn) return `Base ${rate}%${suf}`;
      return `Assiette ${rate}%${suf}`;
    },
    taxAmountRate: (rate:number, included?:boolean)=> {
      const suf = included ? (isAr ? ' (متضمنة)' : isEn ? ' (incl.)' : ' (incl.)') : '';
      if (isAr) return `الضريبة ${rate}%${suf}`;
      if (isEn) return `VAT ${rate}%${suf}`;
      return `TVA ${rate}%${suf}`;
    },
    totalTTC: isAr ? 'المجموع شامل الضريبة' : isEn ? 'Total incl. tax' : 'Total TTC',
    totalHT: isAr ? 'المجموع دون ضريبة' : isEn ? 'Total excl. tax' : 'Total HT',
    orderTitle: isAr ? 'طلب' : isEn ? 'Order' : 'Commande',
    quoteTitle: isAr ? 'عرض سعر' : isEn ? 'Quote' : 'Devis',
    note: isAr ? 'ملاحظة' : isEn ? 'Note' : 'Note',
    amountIntro: isAr ? 'حُدد هذا المستند بمبلغ :' : isEn ? 'This document is set at the amount of:' : 'Arrêté le présent document à la somme de :',
    generatedBy: isAr ? 'مستند تم إنشاؤه بواسطة' : isEn ? 'Document generated by' : 'Document généré par',
    currencyWord: isAr ? 'دينار' : isEn ? 'dinar' : 'dinar',
    // Status map
    statusMap: (raw:string)=> {
      const k = String(raw).trim().toLowerCase();
      const fr: Record<string,string> = { pending:'En attente', pending_payment:'Paiement en attente', processing:'En préparation', shipped:'Expédiée', delivered:'Livrée', cancelled:'Annulée', paid:'Payée', draft:'Brouillon', submitted:'Soumis', replied:'Répondu', revision:'Révision demandée', accepted:'Accepté', rejected:'Refusé', transformed:'Transformé en commande', expired:'Expiré' };
      const en: Record<string,string> = { pending:'Pending', pending_payment:'Pending payment', processing:'Processing', shipped:'Shipped', delivered:'Delivered', cancelled:'Cancelled', paid:'Paid', draft:'Draft', submitted:'Submitted', replied:'Replied', revision:'Revision requested', accepted:'Accepted', rejected:'Rejected', transformed:'Converted to order', expired:'Expired' };
      const ar: Record<string,string> = { pending:'قيد الانتظار', pending_payment:'بانتظار الدفع', processing:'قيد التحضير', shipped:'تم الشحن', delivered:'تم التسليم', cancelled:'ملغى', paid:'مدفوع', draft:'مسودة', submitted:'مرسل', replied:'تم الرد', revision:'طلب مراجعة', accepted:'مقبول', rejected:'مرفوض', transformed:'تم تحويله إلى طلب', expired:'منتهي' };
      if (isAr) return ar[k] || String(raw);
      if (isEn) return en[k] || String(raw);
      return fr[k] || String(raw);
    },
    paymentMap: (raw:string)=> {
      const v = String(raw).toLowerCase();
      const fr: Record<string,string> = { 'card-intl':'Carte internationale','cib':'Carte CIB','transfer':'Virement','virement':'Virement','paypal':'PayPal','check':'Chèque','cod':'Paiement à la livraison','pending':'En attente','other':'Autre' };
      const en: Record<string,string> = { 'card-intl':'International card','cib':'CIB card','transfer':'Transfer','virement':'Transfer','paypal':'PayPal','check':'Check','cod':'Cash on delivery','pending':'Pending','other':'Other' };
      const ar: Record<string,string> = { 'card-intl':'بطاقة دولية','cib':'بطاقة CIB','transfer':'تحويل','virement':'تحويل','paypal':'PayPal','check':'شيك','cod':'الدفع عند التسليم','pending':'قيد الانتظار','other':'أخرى' };
      if (isAr) return ar[v] || String(raw);
      if (isEn) return en[v] || String(raw);
      return fr[v] || String(raw);
    },
  };
}

export interface CompanyInfo {
  name: string;
  tagline?: string;
  phone?: string;
  email?: string;
  address?: string;
  logo?: string;
}

function currencyWord(): string {
  const [word] = defaultCurrency().name.trim().toLowerCase().split(/\s+/);
  return word || 'dinar';
}

const money = (n: number) => {
  const v = Number(n) || 0;
  return `${v.toLocaleString('fr-FR', { minimumFractionDigits: 2, maximumFractionDigits: 2 })} ${defaultCurrency().symbol}`;
};

function escapeHtml(s: string): string {
  return String(s || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/** Génère un barcode SVG simple (Code128-like visuel) à partir du code complet */
function barcodeSvg(code: string): string {
  const c = String(code || '').trim() || 'CODE';
  // Pattern binaire basé sur les charCodes
  let bits = '';
  for (let i = 0; i < c.length; i++) {
    const cc = c.charCodeAt(i);
    for (let b = 7; b >= 0; b--) bits += ((cc >> b) & 1) ? '1' : '0';
  }
  // assure au moins 96 bits pour un rendu stable
  bits = bits.padEnd(96, '1010').slice(0, 96);
  const barW = 2;
  const W = bits.length * barW;
  const H = 42;
  let svg = `<svg width="${W}" height="${H}" viewBox="0 0 ${W} ${H}" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Code-barres ${escapeHtml(c)}">`;
  svg += `<rect width="${W}" height="${H}" fill="white"/>`;
  let x = 0;
  for (let i = 0; i < bits.length; i++) {
    if (bits[i] === '1') svg += `<rect x="${x}" y="6" width="${barW}" height="${H - 14}" fill="#0f172a"/>`;
    x += barW;
  }
  svg += `<text x="${W/2}" y="${H - 1}" text-anchor="middle" font-size="7" font-family="monospace" fill="#334155">${escapeHtml(c)}</text>`;
  svg += `</svg>`;
  return svg;
}

function statusLabel(raw?: string): string {
  if (!raw) return '';
  const k = String(raw).trim().toLowerCase();
  const map: Record<string, string> = {
    pending: 'En attente',
    pending_payment: 'Paiement en attente',
    processing: 'En préparation',
    shipped: 'Expédiée',
    delivered: 'Livrée',
    cancelled: 'Annulée',
    paid: 'Payée',
    draft: 'Brouillon',
    submitted: 'Soumis',
    replied: 'Répondu',
    revision: 'Révision demandée',
    accepted: 'Accepté',
    rejected: 'Refusé',
    transformed: 'Transformé en commande',
    expired: 'Expiré',
  };
  return map[k] || String(raw);
}

/** Structure commune : en-tête société + bloc client + tableau + totaux + montant en lettres + note. */
function documentShell(opts: {
  title: string;
  reference: string;
  date: string;
  validity?: string;
  company: CompanyInfo;
  client: { name: string; email: string; phone?: string; address?: string };
  headers: string[];
  rows: string[][];
  totalLabel: string;
  total: number;
  breakdown?: Array<{ label: string; value: number; muted?: boolean }>;
  note?: string;
  status?: string;
  paymentLabel?: string;
  locale?: PdfLocale | string;
}): string {
  const c = opts.company;
  const tr = pdfT(opts.locale);
  const breakdownHtml = (opts.breakdown || [])
    .map(
      (b) =>
        `<div class="row${b.muted ? ' muted' : ''}"><span>${escapeHtml(b.label)}</span><span class="num">${b.value < 0 ? '-' : ''}${money(Math.abs(b.value))}</span></div>`
    )
    .join('');
  const barcode = barcodeSvg(opts.reference);
  const statutFr = opts.status ? tr.statusMap(opts.status) : '';
  const htmlLang = (opts.locale as string) === 'ar' ? 'ar' : (opts.locale as string) === 'en' ? 'en' : 'fr';
  const htmlDir = htmlLang === 'ar' ? ' dir="rtl"' : '';
  return `<!doctype html>
<html lang="${htmlLang}"${htmlDir}>
<head>
<meta charset="utf-8" />
<title>${escapeHtml(opts.title)} ${escapeHtml(opts.reference)}</title>
<style>
  * { box-sizing: border-box; }
  body { font-family: 'Segoe UI', Arial, sans-serif; color: #1a202c; margin: 0; padding: 32px; }
  .page { max-width: 780px; margin: 0 auto; }
  .head { display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 3px solid #0d7a9e; padding-bottom: 16px; gap: 12px; }
  .brand { display: flex; align-items: center; gap: 12px; }
  .brand img { height: 44px; }
  .brand .name { font-size: 20px; font-weight: 800; color: #0d7a9e; }
  .brand .tag { font-size: 12px; color: #718096; }
  .head .ref { text-align: right; font-size: 12px; color: #4a5568; max-width: 280px; }
  .head .ref h1 { font-size: 22px; margin: 0 0 4px; color: #1a202c; }
  .head .ref .code { font-family: monospace; font-size: 11px; color: #0d7a9e; background: #edf2f7; padding: 2px 6px; border-radius: 4px; display: inline-block; margin-top: 4px; word-break: break-all; }
  .meta { display: flex; justify-content: space-between; gap: 24px; margin: 20px 0; font-size: 13px; }
  .meta .box { flex: 1; }
  .meta .box h3 { font-size: 11px; text-transform: uppercase; letter-spacing: .08em; color: #0d7a9e; margin: 0 0 6px; }
  .meta .box div { color: #4a5568; line-height: 1.6; }
  .meta .box .barcode { margin-top: 10px; }
  .meta .box .barcode svg { max-width: 100%; height: auto; display: block; }
  table { width: 100%; border-collapse: collapse; margin-top: 8px; font-size: 13px; }
  th { background: #edf2f7; text-align: left; padding: 8px 10px; font-size: 11px; text-transform: uppercase; letter-spacing: .05em; color: #4a5568; }
  td { padding: 8px 10px; border-bottom: 1px solid #e2e8f0; }
  .num { text-align: right; font-variant-numeric: tabular-nums; white-space: nowrap; }
  .totals { margin-left: auto; width: 360px; margin-top: 16px; font-size: 13px; border: 1px solid #e2e8f0; border-radius: 8px; padding: 10px 14px; background: #f8fafc; }
  .totals .row { display: flex; justify-content: space-between; padding: 4px 0; color: #4a5568; border-bottom: 1px dashed #e2e8f0; }
  .totals .row.muted { color: #718096; font-size: 12px; }
  .totals .row:last-child { border-bottom: none; }
  .totals .grand { display: flex; justify-content: space-between; font-size: 16px; font-weight: 800; border-top: 2px solid #0d7a9e; padding-top: 8px; margin-top: 6px; color: #0d7a9e; }
  .letters { margin-top: 20px; padding: 12px 14px; border: 1px dashed #a0aec0; border-radius: 6px; font-size: 13px; }
  .letters b { color: #0d7a9e; }
  .note { margin-top: 16px; font-size: 12px; color: #4a5568; white-space: pre-wrap; }
  .foot { margin-top: 32px; border-top: 1px solid #e2e8f0; padding-top: 12px; font-size: 11px; color: #a0aec0; text-align: center; }
  @media print { body { padding: 0; } .totals { background: white; } }
</style>
</head>
<body>
<div class="page">
  <div class="head">
    <div class="brand">
      ${c.logo ? `<img src="${escapeHtml(c.logo)}" alt="" />` : ''}
      <div>
        <div class="name">${escapeHtml(c.name)}</div>
        ${c.tagline ? `<div class="tag">${escapeHtml(c.tagline)}</div>` : ''}
      </div>
    </div>
    <div class="ref">
      <h1>${escapeHtml(opts.title)}</h1>
      <div class="code">${escapeHtml(opts.reference)}</div>
    </div>
  </div>

  <div class="meta">
    <div class="box">
      <h3>${tr.issuer}</h3>
      <div>
        ${escapeHtml(c.name)}<br/>
        ${escapeHtml(c.address || '')}<br/>
        ${c.phone ? `${tr.phone} : ${escapeHtml(c.phone)}<br/>` : ''}
        ${c.email ? escapeHtml(c.email) : ''}
      </div>
    </div>
    <div class="box">
      <h3>${tr.client}</h3>
      <div>
        ${escapeHtml(opts.client.name)}<br/>
        ${escapeHtml(opts.client.email)}<br/>
        ${opts.client.phone ? `${tr.phone} : ${escapeHtml(opts.client.phone)}<br/>` : ''}
        ${opts.client.address ? escapeHtml(opts.client.address) : ''}
      </div>
    </div>
    <div class="box">
      <h3>${tr.document}</h3>
      <div>
        ${tr.date} : ${escapeHtml(opts.date)}<br/>
        ${tr.ref} : ${escapeHtml(opts.reference)}<br/>
        ${opts.validity ? `${tr.validity} : ${escapeHtml(opts.validity)}<br/>` : ''}
        ${statutFr ? `${tr.status} : ${escapeHtml(statutFr)}<br/>` : ''}
        ${opts.paymentLabel ? `${tr.paymentMode} : ${escapeHtml(opts.paymentLabel)}<br/>` : ''}
        <div class="barcode">${barcode}</div>
      </div>
    </div>
  </div>

  <table>
    <thead><tr>${opts.headers.map((h) => `<th>${escapeHtml(h)}</th>`).join('')}</tr></thead>
    <tbody>
      ${opts.rows.map((r) => `<tr>${r.map((cell) => `<td>${cell}</td>`).join('')}</tr>`).join('')}
    </tbody>
  </table>

  <div class="totals">
    ${breakdownHtml}
    ${opts.totalLabel !== '' ? `<div class="grand"><span>${escapeHtml(opts.totalLabel)}</span><span>${money(opts.total)}</span></div>` : ''}
  </div>

  <div class="letters">
    ${tr.amountIntro} <b>${escapeHtml(amountInWords(opts.total, tr.currencyWord, opts.locale as string))}</b>.
  </div>

  ${opts.note ? `<div class="note"><b>${tr.note} :</b> ${escapeHtml(opts.note)}</div>` : ''}

  <div class="foot">${escapeHtml(c.name)} — ${escapeHtml(c.address || '')} — ${tr.generatedBy} SARI CMS — ${escapeHtml(opts.reference)}</div>
</div>
</body>
</html>`;
}

/**
 * Totaux tels que les calcule `computeTotals` (`lib/commerce-math.ts`).
 * Seuls les champs affichés par le document sont requis.
 */
export interface DocTotals {
  subtotal: number;
  discount: number;
  productDiscount: number;
  globalDiscount: number;
  couponDiscount: number;
  shipping: number;
  productShipping: number;
  globalShipping: number;
  taxLines: Array<{ id: string; name: string; rate: number; mode: string; amount: number; base?: number; included?: boolean }>;
  taxTotal: number;
  total: number;
}

/**
 * Prépare un document (commande ou devis) pour l'impression en y appliquant les
 * totaux calculés.
 *
 * La fiche de l'admin n'affiche pas les montants stockés sur la ligne : elle les
 * recalcule à chaque rendu à partir des articles, des règles de taxe, des
 * coupons et de la zone de livraison. Sans cette étape, le PDF partait de la
 * ligne brute et restait muet sur la TVA, la remise globale et la livraison dès
 * que ces champs n'avaient jamais été persistés — alors que la fiche, elle,
 * affichait tout. Le document imprimé montre donc exactement ce que l'écran
 * montre.
 *
 * Passer `null` laisse le document intact (document différent de celui calculé).
 */
export function withTotals<T extends object>(doc: T, totals: DocTotals | null | undefined): T {
  if (!totals) return doc;
  return {
    ...doc,
    subtotal: totals.subtotal,
    productDiscount: totals.productDiscount,
    globalDiscount: totals.globalDiscount,
    couponDiscount: totals.couponDiscount,
    discountTotal: totals.discount,
    productShipping: totals.productShipping,
    globalShipping: totals.globalShipping,
    shippingFee: totals.shipping,
    taxLines: totals.taxLines,
    taxTotal: totals.taxTotal,
    total: totals.total,
  } as T;
}

/** Template PDF pour un devis (utilise la réponse détaillée si présente, sinon les lignes de la demande). */
export function quotePdfHtml(quote: Quote, company: CompanyInfo, locale?: PdfLocale | string): string {
  const source = quote.response?.mode === 'detailed' && quote.response.lines
    ? quote.response.lines.map((l) => ({
        name: l.name,
        quantity: l.quantity,
        unitPrice: l.unitPrice,
        discount: l.discount || 0,
      }))
    : (quote.items || []).map((it) => ({
        name: it.name,
        quantity: it.quantity,
        unitPrice: it.price,
        discount: (it as any).discountValue ?? it.discount ?? 0,
        discountType: (it as any).discountType || 'percent',
      }));

  const rows = source.map((l: any) => {
    const discVal = Number(l.discount || 0);
    const discType = l.discountType || 'percent';
    const lineTotal =
      discType === 'fixed'
        ? (l.quantity || 0) * (l.unitPrice || 0) - discVal * (l.quantity || 0)
        : (l.quantity || 0) * (l.unitPrice || 0) * (1 - discVal / 100);
    const discLabel = discVal ? (discType === 'fixed' ? `-${money(discVal)}` : `-${discVal}%`) : '—';
    return [
      escapeHtml(l.name),
      `<span class="num">${l.quantity}</span>`,
      `<span class="num">${money(l.unitPrice)}</span>`,
      `<span class="num">${discLabel}</span>`,
      `<span class="num">${money(Math.max(0, lineTotal))}</span>`,
    ];
  });

  const total = quote.response?.total ?? (quote as any).total ?? 0;
  const reference = quote.reference || `DV #${quote.id}`;
  const qAny = quote as any;
  const tr = pdfT(locale);
  const breakdown: Array<{ label: string; value: number; muted?: boolean }> = [];
  // Subtotal: stored or compute from lines
  const subtotal = typeof qAny.subtotal === 'number' ? qAny.subtotal : source.reduce((s:number,l:any)=> s + Number(l.unitPrice||0)*Number(l.quantity||0),0);
  breakdown.push({ label: tr.subtotal, value: subtotal });
  // Remises: détaille produit / globale / coupon si présents, sinon fallback
  if (typeof qAny.productDiscount === 'number' && qAny.productDiscount > 0) breakdown.push({ label: tr.productDiscount, value: -qAny.productDiscount, muted: true });
  if (typeof qAny.globalDiscount === 'number' && qAny.globalDiscount > 0) breakdown.push({ label: tr.globalDiscount, value: -qAny.globalDiscount, muted: true });
  if (typeof qAny.couponDiscount === 'number' && qAny.couponDiscount > 0) breakdown.push({ label: tr.couponDiscount(qAny.coupon || ''), value: -qAny.couponDiscount, muted: true });
  if (typeof qAny.discountTotal === 'number' && qAny.discountTotal > 0 && !qAny.productDiscount && !qAny.globalDiscount && !qAny.couponDiscount) breakdown.push({ label: tr.discounts, value: -qAny.discountTotal, muted: true });
  else if (typeof qAny.discount === 'number' && qAny.discount > 0 && !qAny.productDiscount) breakdown.push({ label: tr.discount, value: -qAny.discount, muted: true });
  // Livraison: produit + zone + fallback
  if (typeof qAny.productShipping === 'number' && qAny.productShipping > 0) breakdown.push({ label: tr.productShipping, value: qAny.productShipping });
  if (typeof qAny.globalShipping === 'number' && qAny.globalShipping > 0) breakdown.push({ label: tr.globalShipping, value: qAny.globalShipping });
  if (typeof qAny.shippingFee === 'number' && qAny.shippingFee > 0 && !qAny.productShipping && !qAny.globalShipping) breakdown.push({ label: tr.shipping, value: qAny.shippingFee });
  else if (typeof qAny.deliveryFee === 'number' && qAny.deliveryFee > 0 && !qAny.productShipping && !qAny.globalShipping) breakdown.push({ label: tr.shipping, value: qAny.deliveryFee });
  else if (typeof qAny.shipping === 'number' && qAny.shipping > 0 && !qAny.productShipping && !qAny.globalShipping) breakdown.push({ label: tr.shipping, value: qAny.shipping });
  // TVA: détaille par taux avec assiette + montant
  if (Array.isArray(qAny.taxLines) && qAny.taxLines.length) {
    const valid = (qAny.taxLines as any[]).filter((tl:any)=> tl && typeof tl==='object' && !Array.isArray(tl) && tl.name && typeof tl.amount==='number' && Number.isFinite(tl.amount) && tl.amount!==0);
    if (valid.length) {
      const grouped = new Map<number, { base:number; amount:number; included:boolean }>();
      for (const tl of valid) {
        const rate = Number(tl.rate)||0;
        const inc = !!tl.included;
        let base:number;
        if (typeof tl.base==='number' && Number.isFinite(tl.base)) base=tl.base;
        else if (tl.mode==='percent' && rate) base= tl.amount/(rate/100);
        else if (rate) base= tl.amount/(rate/100);
        else base=0;
        const g=grouped.get(rate);
        if(g){ g.base+=base; g.amount+=tl.amount; } else grouped.set(rate,{base, amount:tl.amount, included:inc});
      }
      if (grouped.size===1 && valid.length===1) {
        const tl:any=valid[0]; const rate=Number(tl.rate)||0; const g=grouped.get(rate)!;
        if(g.base>0.005 && tl.mode!=='fixed') breakdown.push({ label: tr.taxBaseRate(rate, g.included), value:g.base, muted:true });
        breakdown.push({ label: tr.taxAmountRate(rate, g.included), value:g.amount, muted:true });
      } else {
        for(const [rate,g] of Array.from(grouped.entries()).sort((a,b)=>a[0]-b[0])){
          if(rate===0 && g.base===0) breakdown.push({ label: tr.tax, value:g.amount, muted:true });
          else { if(g.base>0.005) breakdown.push({ label: tr.taxBaseRate(rate, g.included), value:g.base, muted:true }); breakdown.push({ label: tr.taxAmountRate(rate, g.included), value:g.amount, muted:true }); }
        }
      }
    }
    if (!valid.length && typeof qAny.taxTotal === 'number' && qAny.taxTotal > 0) breakdown.push({ label: tr.tax, value: qAny.taxTotal, muted: true });
  } else if (typeof qAny.taxTotal === 'number' && qAny.taxTotal > 0) {
    breakdown.push({ label: tr.tax, value: qAny.taxTotal, muted: true });
  } else if (typeof qAny.tax === 'number' && qAny.tax > 0) {
    breakdown.push({ label: tr.tax, value: qAny.tax, muted: true });
  }

  return documentShell({
    title: tr.quoteTitle,
    reference,
    date: quote.date,
    validity: quote.validity || undefined,
    company,
    client: { name: quote.client, email: quote.email, phone: quote.phone, address: quote.address },
    headers: tr.headers,
    rows,
    totalLabel: tr.totalTTC,
    total,
    breakdown,
    note: quote.note,
    status: quote.status,
    locale,
  });
}

/** Template PDF pour une commande. */
export function orderPdfHtml(order: Order, company: CompanyInfo, locale?: PdfLocale | string): string {
  const rows = (order.items || []).map((it: any) => {
    const discVal = Number(it.discountValue ?? it.discount ?? 0);
    const discType = it.discountType || 'percent';
    const base = (it.quantity || 0) * (it.price || 0);
    const lineTotal = discType === 'fixed' ? base - discVal * (it.quantity || 0) : base * (1 - discVal / 100);
    const discLabel = discVal ? (discType === 'fixed' ? `-${money(discVal)}` : `-${discVal}%`) : '—';
    return [
      escapeHtml(it.name),
      `<span class="num">${it.quantity}</span>`,
      `<span class="num">${money(it.price)}</span>`,
      `<span class="num">${discLabel}</span>`,
      `<span class="num">${money(Math.max(0, lineTotal))}</span>`,
    ];
  });

  const oAny = order as any;
  const reference = order.code || `#${order.id}`;
  const tr = pdfT(locale);
  const breakdown: Array<{ label: string; value: number; muted?: boolean }> = [];
  const subtotal = typeof oAny.subtotal === 'number' ? oAny.subtotal : (order.items || []).reduce((s: number, it: any) => s + Number(it.price || 0) * Number(it.quantity || 0), 0);
  breakdown.push({ label: tr.subtotal, value: subtotal });
  if (typeof oAny.productDiscount === 'number' && oAny.productDiscount > 0) breakdown.push({ label: tr.productDiscount, value: -oAny.productDiscount, muted: true });
  if (typeof oAny.globalDiscount === 'number' && oAny.globalDiscount > 0) breakdown.push({ label: tr.globalDiscount, value: -oAny.globalDiscount, muted: true });
  if (typeof oAny.couponDiscount === 'number' && oAny.couponDiscount > 0) breakdown.push({ label: tr.couponDiscount(oAny.coupon || ''), value: -oAny.couponDiscount, muted: true });
  // Repli « Remises » agrégé : seulement si aucun détail n'est affiché. La
  // fiche commande exige aussi `couponDiscount === 0` — sans cette garde, un
  // document avec un simple coupon afficherait la remise du coupon PUIS le
  // total des remises, donc la même remise deux fois.
  if (typeof oAny.discountTotal === 'number' && oAny.discountTotal > 0 && !oAny.productDiscount && !oAny.globalDiscount && !oAny.couponDiscount) breakdown.push({ label: tr.discounts, value: -oAny.discountTotal, muted: true });
  else if (typeof oAny.discount === 'number' && oAny.discount > 0 && !oAny.productDiscount && !oAny.globalDiscount && !oAny.couponDiscount) breakdown.push({ label: tr.discount, value: -oAny.discount, muted: true });
  if (oAny.productShipping > 0) breakdown.push({ label: tr.productShipping, value: oAny.productShipping });
  if (oAny.globalShipping > 0) breakdown.push({ label: tr.globalShipping, value: oAny.globalShipping });
  if (typeof oAny.shippingFee === 'number' && oAny.shippingFee > 0 && !oAny.productShipping && !oAny.globalShipping) breakdown.push({ label: tr.shipping, value: oAny.shippingFee });
  else if (typeof oAny.deliveryFee === 'number' && oAny.deliveryFee > 0 && !oAny.productShipping && !oAny.globalShipping) breakdown.push({ label: tr.shipping, value: oAny.deliveryFee });
  else if (typeof oAny.shipping === 'number' && oAny.shipping > 0 && !oAny.productShipping && !oAny.globalShipping) breakdown.push({ label: tr.shipping, value: oAny.shipping });
  // Livraison offerte 0 supprimée (bruit visuel) — le total suffit, ou afficher seulement si explicitement offerte via globalShipping=0
  // if (typeof oAny.shipping === 'number' && oAny.shipping === 0) breakdown.push({ label: 'Livraison offerte', value: 0 });
  if (Array.isArray(oAny.taxLines) && oAny.taxLines.length) {
    const validTaxLines = (oAny.taxLines as any[]).filter((tl:any)=> tl && typeof tl==='object' && !Array.isArray(tl) && tl.name && typeof tl.amount==='number' && Number.isFinite(tl.amount) && tl.amount!==0);
    if (validTaxLines.length) {
      // Groupe par taux pour afficher assiette + taxe par taux (demande : assiette de taxe par taux)
      const grouped = new Map<number, { base:number; amount:number; included:boolean }>();
      for (const tl of validTaxLines) {
        const rate = Number(tl.rate) || 0;
        const inc = !!tl.included;
        let base: number;
        if (typeof tl.base === 'number' && Number.isFinite(tl.base)) base = tl.base;
        else if (tl.mode === 'percent' && rate) base = tl.amount / (rate/100);
        else if (rate) base = tl.amount / (rate/100);
        else base = 0;
        const g = grouped.get(rate);
        if (g) { g.base += base; g.amount += tl.amount; }
        else grouped.set(rate, { base, amount: tl.amount, included: inc });
      }
      // Si un seul taux et un seul trait, garde le label d'origine (ex: TVA produit avec nom produit)
      if (grouped.size === 1 && validTaxLines.length === 1) {
        const tl: any = validTaxLines[0];
        const rate = Number(tl.rate) || 0;
        const g = grouped.get(rate)!;
        if (g.base > 0.005 && tl.mode !== 'fixed') breakdown.push({ label: tr.taxBaseRate(rate, g.included), value: g.base, muted: true });
        breakdown.push({ label: tr.taxAmountRate(rate, g.included), value: g.amount, muted: true });
      } else {
        for (const [rate, g] of Array.from(grouped.entries()).sort((a,b)=> a[0]-b[0])) {
          if (rate === 0 && g.base === 0) { // taxe fixe sans taux
            breakdown.push({ label: tr.tax, value: g.amount, muted: true });
          } else {
            if (g.base > 0.005) breakdown.push({ label: tr.taxBaseRate(rate, g.included), value: g.base, muted: true });
            breakdown.push({ label: tr.taxAmountRate(rate, g.included), value: g.amount, muted: true });
          }
        }
      }
    }
    if (!validTaxLines.length && typeof oAny.taxTotal === 'number' && oAny.taxTotal > 0) breakdown.push({ label: tr.tax, value: oAny.taxTotal, muted: true });
    else if (!validTaxLines.length && typeof oAny.tax === 'number' && oAny.tax > 0) breakdown.push({ label: tr.tax, value: oAny.tax, muted: true });
  } else if (typeof oAny.taxTotal === 'number' && oAny.taxTotal > 0) {
    breakdown.push({ label: tr.tax, value: oAny.taxTotal, muted: true });
  } else if (typeof oAny.tax === 'number' && oAny.tax > 0) {
    breakdown.push({ label: tr.tax, value: oAny.tax, muted: true });
  }

  const total = oAny.total ?? 0;
  // Résout le label paiement pour affichage dans le PDF
  let paymentLabel: string | undefined;
  try {
    const raw = oAny.payment;
    if (raw) {
      paymentLabel = tr.paymentMap(String(raw));
    }
  } catch {}

  return documentShell({
    title: tr.orderTitle,
    reference,
    date: order.date,
    company,
    client: { name: order.client, email: order.email, phone: order.phone, address: order.address },
    headers: tr.headers,
    rows,
    totalLabel: tr.totalTTC,
    total,
    breakdown,
    note: oAny.adminNotes || oAny.notes || order.items?.find((i: any) => i.description)?.description,
    status: order.status,
    paymentLabel,
    locale,
  });
}

/** Ouvre une fenêtre et lance l'impression (enregistrer en PDF). */
export function printHtml(title: string, html: string): void {
  const w = window.open('', '_blank', 'width=900,height=1000');
  if (!w) return;
  w.document.open();
  w.document.write(html);
  w.document.close();
  w.document.title = title;
  w.focus();
  setTimeout(() => w.print(), 350);
}
